### ISSUE TITLE
Project Full Screen User List still buggy

### ISSUE THREAD

**Issue by jorgenevil** [systemapic/systemapic.js#155] opened 2016-02-24 14:49 UTC
There are several bugs with this:
- [x] drop down menu starts open
- [x] too few people in list (in this project, it should be 40 editors, while only two are showing)
- [x] when leave the fullscreen and come back again, no users are shown (editors and viewer lists are completely empty.

As you see in the console, the error `Cannot read property 'getFullName' of undefined` appears on this line: https://github.com/systemapic/systemapic.js/blob/1cc6fe9066c9f221032647f30744daf51c534c8d/js/src/chrome/projects/chrome.projects.js#L993

First time opening full screen:
![screen shot 2016-02-24 at 3 47 06 pm](https://cloud.githubusercontent.com/assets/8961926/13288820/e574c8d0-db0d-11e5-8df2-dc8e9e85006b.png)

Second time opening full screen:
![screen shot 2016-02-24 at 3 48 47 pm](https://cloud.githubusercontent.com/assets/8961926/13288873/1ecc5cf6-db0e-11e5-8792-feaed84a9625.png)

**Comment by jorgenevil** [comment] 2016-02-24 17:03
This is what it looks like:
![full-pane](https://cloud.githubusercontent.com/assets/8961926/13293667/d7ef245e-db20-11e5-99fa-a65fcbc87a34.gif)

**Comment by knutole** [comment] 2016-02-24 17:05
Wow, great BUG FEEDBACK bro! :)

**Comment by knutole** [comment] 2016-02-24 17:07
@IgorZiegler You can download http://www.cockos.com/licecap/ to create GIF's for issues :)

**Comment by IgorZiegler** [comment] 2016-02-26 05:33
@knutole @jorgenevil Could you shared this project with me? I have a problem with reproduce it.

**Comment by jorgenevil** [comment] 2016-02-26 09:14
@IgorZiegler You should already be an editor of this project, on beta server:
`https://beta.systemapic.com/jorgen/demonve`

**Comment by IgorZiegler** [comment] 2016-02-26 10:23
@jorgenevil i have not account on beta server=)

**Comment by IgorZiegler** [comment] 2016-02-26 14:10
@knutole @jorgenevil  in [this line](https://github.com/systemapic/systemapic.js/blob/bc9f6123f612497722c6d751647aecaaa9cdd827/js/src/chrome/projects/chrome.projects.js#L992) we have `user-a3eef95c-f46a-407c-8109-b62fb36badf2` in userUuid variable, but app.Users[userUuid] doesn't exist.

**Comment by knutole** [comment] 2016-02-26 14:19
@IgorZiegler Yes, this is probably due to mismatch between available users and which users have access. (Or perhaps user was deleted...)  Can you create a separate issue for this?

**Comment by IgorZiegler** [comment] 2016-02-26 14:29
@knutole created [here](https://github.com/systemapic/systemapic.js/issues/163)

**Comment by IgorZiegler** [comment] 2016-02-26 15:07
@knutole could we check what user is it `user-a3eef95c-f46a-407c-8109-b62fb36badf2`?

**Comment by knutole** [comment] 2016-02-26 15:09
@IgorZiegler Nope, the user is deleted. I think that's the problem here. So solution, anyway, is just to add a check so that there's no error anyway. I will research the underlying issue.

**Comment by knutole** [comment] 2016-02-26 23:56
@IgorZiegler Sorry to say, but there keeps popping up more bugs with this. Now the search is not working...

EDIT: NEVERMIND! This bug was introduced by myself in last "fix"... Sorry;)

![invite_bug](https://cloud.githubusercontent.com/assets/2197944/13368653/a4b91d56-dcec-11e5-9870-e537a4289199.gif)

**Comment by knutole** [comment] 2016-02-27 01:23
Fixed some of these bugs, but want to keep this issue open, as I'm not sure all bugs are gone.

Some serious _bugtesting_ needs to be done here.

**Comment by IgorZiegler** [comment] 2016-02-29 05:29
@knutole As I see it filter works correctly now.

**Comment by knutole** [comment] 2016-02-29 16:41
Closing this, will open new issue if more bugs.

**Closed as completed by knutole** 2016-02-29 16:41 UTC
Labels: bug, priority
